### ISSUE TITLE
plugin not working with VCD 10.1

### ISSUE THREAD

**Issue by vpaule** [cohesity/cohesity-vcd-extension#1]
The plugin is not working in VCD 10.1, the entry "Data Protection" is created in the new "more" menu, but when you click on it, nothing happens.
Could you please have a look and help us out?
We are working with the latest cohesity release (6.5.0a_release-20200425_732a83e6), but the connection to the cohesity cluster can't be made, as long as we can't configure the plugin as nothing can be seen.

**Comment by shubhamkr-cohesity** [comment]
We have yet not certified VCD 10.1 @vpaule  Latest version certified is v10.0 with plugin v1.3.0. 

We are working on the qualification for vCD 10.1

**Comment by vpaule** [comment]
> We have yet not certified VCD 10.1 @vpaule Latest version certified is v10.0 with plugin v1.3.0.
> 
> We are working on the qualification for vCD 10.1

Thanks for your reply. When do you think will the plugin be ready for VCD 10.1? We are currently testing the Cohesity backup solution but without a compatible plugin for VCD10.1 we can't take this setup into production.

**Comment by vpaule** [comment]
Any update on the compatibility? We are still not able to use the plugin.

**Comment by shubhamkr-cohesity** [comment]
Hi @vpaule,
I would request you to please reach out through the Cohesity support channel. 
Currently none of the Cohesity cluster versions (including 6.5.0a) have been qualified with vCD 10.1.
