### ISSUE TITLE
VCD 10.3.1 and newer

### ISSUE THREAD

**Issue by burnziii** [cohesity/cohesity-vcd-extension#10]
When will VCD 10.3.1 and 10.3.2 be supported?
As VCD 10.3.1 is out since 14th october and 10.3.2 since 10th january our VM guys ask when we are ready to backup these VCD versions.

**Comment by shubhamkr-cohesity** [comment]
Hi @burnziii ,
We do have support for 10.3.2 as well with our latest releases. Please reach out to cohesity support. They will assist you.

Thank you.
