### ISSUE TITLE
Pre-Release Versions?

### ISSUE THREAD

**Issue by burnziii** [cohesity/cohesity-vcd-extension#11]
We would like to know if pre-release versions are recommended for production environment, or if you only recommend these versions for testing?

As we are planning to upgrade to 6.8 cluster version, we need VCD extension to fully supported.
Is there any roadmap for release version 2.3.3?

**Comment by shubhamkr-cohesity** [comment]
Hi @burnziii ,
We have marked v2.3.3 as production ready.

This is supported with cluster v6.8

Thanks.
