### ISSUE TITLE
vcd mapping expires

### ISSUE THREAD

**Issue by burnziii** [cohesity/cohesity-vcd-extension#13]
As the maximum password lifetime setting for a cohesity user is 365 days.
This causes issues with vcd org to Cohesity org mapping due to expiring passwords.

Is there any possibility to use api keys instead of passwords or is there any possibility to use "service users" which don't have expiring passwords?

**Comment by shubhamkr-cohesity** [comment]
@burnziii The current workaround is to disable expiry of passwords for local users using gflags. 
You can reach out to the support for the gflag information.
