### ISSUE TITLE
Unable to map organizations from multiple clusters

### ISSUE THREAD

**Issue by fs-monacocloud** [cohesity/cohesity-vcd-extension#15]
## 🐛 Bug Report

I am trying to map a single vCD tenant to 2 organizations from different clusters so that the user can backup using the cluster it wants but when I do so, the user is unable to select a storage domain because the menu is empty.

## To Reproduce

1. Setup two clusters as expected
2. Check the extension works with a single cluster mapped
3. Map the second cluster
4. Check if it is possible to backup from the extension

![image](https://user-images.githubusercontent.com/129410275/228878087-53dc5830-7c80-43e2-8ef9-232314cf226f.png)

## Expected behavior

The use should be able to select a storage domain from one of the clusters

## Actual Behavior

There is no storage domain available

**Comment by shubhamkr-cohesity** [comment]
1. Is a storage domain assigned to the tenant in Cohesity cluster 'lab-backup' ?
2. Can you share the browser console logs?
