### ISSUE TITLE
Recover files or folders

### ISSUE THREAD

**Issue by sarbaron** [cohesity/cohesity-vcd-extension#5]
## 🐛 Bug Report

VCD Version:  10.1.2.16779297

Restore files/folders when using "Browse or Specify path" if the files are not indexed it seems that I cannot restore.

## To Reproduce

1. try and restore a file from /VAR on a Linux machine

## Expected behavior

I want to be able to restore to the original location/alternate location and download locally.

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

**Comment by shubhamkr-cohesity** [comment]
Closing as it could not be reproduced.
