### ISSUE TITLE
Recover File/Folder -> Download file = not working

### ISSUE THREAD

**Issue by magnuslarss** [cohesity/cohesity-vcd-extension#6]
## 🐛 Bug Report

When doing file/folder level recovery through search for file the download button just opens another tab to Cloud Director.
When logging into the Cohesity GUI the file download works.
Cloud Director 10.1.2.16779297
Cohesity 6.5.1d Hotfix4
vcd-extension 2.0.3

## To Reproduce

(Write your steps here:)

1. Search for a file to recover
2. Select a file and download
3. Go to the monitor tab and open the link to the job when finished and click the download link
4. A new browser tab opens but no file downloads, no error message visible

**Comment by shubhamkr-cohesity** [comment]
Hi @magnuslarss ,
We had issue with file download in vCD 10+ & extension 2.x.

This has been resolved in the latest release.
