### ISSUE TITLE
File/Folder recovery -> Browse or Specify path -> download option not available

### ISSUE THREAD

**Issue by magnuslarss** [cohesity/cohesity-vcd-extension#7]
## 🐛 Bug Report

When doing File/Folder recovery through the Browse or Specify path option the download now option is not available

## To Reproduce

1. Open File/Folder recovery and select Browse or specify path option
2. Find something to recover and the next step is restore to server page
3. Download now option is not available in this recovery flow

## Actual Behavior

When doing recovery through search files and folders
![image](https://user-images.githubusercontent.com/84007750/117779614-1f22f300-b23f-11eb-85b4-aa8c0f9ecca4.png)

When doing recovery through browse or specify path
![image](https://user-images.githubusercontent.com/84007750/117779825-57c2cc80-b23f-11eb-9384-c47535b9b87e.png)

**Comment by shubhamkr-cohesity** [comment]
Currently we don't support this. We have added this in our pipeline. Will update once this feature is available.
