### ISSUE TITLE
Plugin 2.1.0 VCD 10.2.2 File Restore to VM not working

### ISSUE THREAD

**Issue by thomaspaulsen** [cohesity/cohesity-vcd-extension#8]
## 🐛 Bug Report
When trying to restore a file or folder to another VM in VCD, you can select all the settings, but when you want to continue, the following error is shown:
![image](https://user-images.githubusercontent.com/87020802/124604105-e718e480-de6a-11eb-85e6-c1b9caabfaf3.png)
"Unable to perform this action. Contant your cloud administrator."

## To Reproduce
1. Go to "Data Protection" > "Recovery"
2. Select "Recover > Files and Folders"
3. Select "Files and Folder" or "Browse or Specify path"
4. Select Source VM which has been backed up before.
5. Browse the path, select the File or Folder you want to restore. Click "Continue"
6. Select oVDC, vApp, VM, OS Type, Enter Credentials, Select snapshot.
7. Recovery Method: "Use VMware Tools"
8. Select "Recover to New location"
9. Enter new location at "Recover to" (f.e. "/tmp"
10. Click Restore.
11. See error message

## Expected behavior

I was expecting the Plugin to call Cohesity to do a restore using the VMware Tools.

## Actual Behavior

Error message, see above.

**Comment by shubhamkr-cohesity** [comment]
There were issues with recovery of non-indexed files. This issue has been fixed v2.2.0
